name: Ubuntu release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CC: gcc
    steps:
    - uses: actions/checkout@v4

    - name: Install stuff for creating packages
      run: sudo apt install -y fakeroot rpm dpkg debhelper

    - name: Install packages required for optional configurations of cntlm
      run: sudo apt install -y libkrb5-dev

    - name: Install further tools (clang-tools for scan-build)
      run: sudo apt install -y clang-tools

    - name: Build artifact
      run: |
        ./configure
        make
        make rpm
        make deb
    
    - name: Extract and format version
      id: format_version
      run: |
        version=$(echo "${{ github.ref }}" | sed 's/refs\/tags\///')
        echo "::set-output name=VERSION::$version"
      shell: bash

    - name: Create or Update Release
      id: create_or_update_release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          cntlm*.rpm
          cntlm*.deb
        tag_name: ${{ steps.format_version.outputs.VERSION }} 
        name: Release ${{ steps.format_version.outputs.VERSION }} 

